services:
  api:
    image: Paulojoserc/clinicamedagil-api:latest # Use a imagem do Docker Hub
    container_name: backend
    # Remova a seção 'build: .' daqui no servidor
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db_cliagil
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - clianet

  # SERVIÇO DO BANCO DE DADOS
  postgres:
    image: postgres:16-alpine
    container_name: clinicamedagil-postgres
    platform: linux/arm64  # <--- Garante que o Postgres também suba em ARM
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_cliagil
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_cliagil"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - clianet

volumes:
  postgres_data:

networks:
  clianet:
    driver: bridge
