spring.application.name=clinicamedagil
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/db_cliagil}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
app.seed.enabled=${APP_SEED_ENABLED:true}
app.seed.default-secret=${APP_SEED_DEFAULT_SECRET:123456}

jwt.secret=0123456789012345678901234567890123456789012345678901234567890123
jwt.expiration=86400000

server.port=8081
#server.servlet.context-path=/clinicamedagil
