name: Deploy Backend OCI

on:
  push:
    branches: [ "main" ] # Só dispara quando houver push na main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/clinicamedagil-api:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/clinicamedagil-api:latest

      - name: Deploy to OCI via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_VM_IP_BACK }}
          username: ubuntu
          key: ${{ secrets.OCI_SSH_KEY_BACK }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/clinicamedagil-api:latest
            sudo docker stop backend || true
            sudo docker rm backend || true
            sudo docker run -d --name backend -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/clinicamedagil-api:latest
            
            # ... passos anteriores de Setup Java e Login Docker Hub ...

      - name: Build and Push with Docker Compose
        run: |
          # O build usa o arquivo docker-compose.yml para saber como montar a imagem
           docker compose build
            docker compose push

      - name: Deploy to OCI via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_VM_IP_BACK }}
          username: ubuntu
          key: ${{ secrets.OCI_SSH_KEY_BACK }}
          script: |
         # Entra na pasta do projeto (ajuste o caminho se necessário)
              cd ~/clinicamedagil-api 
              sudo docker compose pull
              sudo docker compose up -d